### ISSUE TITLE
WebClient not supporting concurrent I/O operations

### ISSUE THREAD

**Issue by FabianZimbalev** [ovh/csharp-ovh#28] opened 2019-07-11 08:58 UTC
Hi,

I´m getting some exceptions with WebClients not supporting concurrent I/O operations.

`
11.07.2019 09:46:26 WebClient unterstützt keine gleichzeitigen E/A-Vorgänge. 
11.07.2019 09:46:26    bei System.Net.WebClient.ClearWebClientState()
   bei System.Net.WebClient.DownloadString(Uri address)
   bei System.Net.WebClient.DownloadString(String address)
   bei Ovh.Api.Client.Call(String method, String path, String data, Boolean needAuth, Boolean isBatch)
   bei Ovh.Api.Client.Call[T](String method, String path, String data, Boolean needAuth, Boolean isBatch)
   bei Ovh.Api.Client.Get[T](String target, QueryStringParams kwargs, Boolean needAuth)
   bei OVHDomainSwitcher.Service.<>c__DisplayClass8_0.<OnStart>b__0(Object state) in E:\workspace\vs2017\ovhdomainswitcher\OVHDomainSwitcher\OVHDomainSwitcher\Service.cs:Zeile 172. `

I use the "Get<>" method so I don´t think it´s async and I run it  in sync on a for loop so a call and only execute when the pevious already finished, that causes some confusion on my side. 
Could you check if the issue might be caused inside the API in any way ?

That´s my logic in pseudo-code:

ovh.getDomains()   
foreach(domain in domains){  
    ovh.Get(RecordIDs)  
    ovh.Get(RecordID/Target)  
    if(ping target != success) {  
        ovh.Post(RecordID/Target, newIP)  
    }  
}  

Best regards,
Fabian

**Comment by LukeMarlin** [comment] 2019-07-11 09:46
As far as I understand, it cannot be caused by the API itself, it has something to do with csharp-ovh.
I'll look into it.

On the other hand, I've been thinking of replacing `WebClient` with the newer `HttpClient`, which does not support synchronous stuff anymore and relies on async/await...

**Comment by FabianZimbalev** [comment] 2019-07-11 09:51
Yes, sorry if I was unclear on this, that is related to the WebClient which is used in csharp-ovh.
Also, as far as I´m informed, the HttpClient is Thread-save and allows multiple reuqests at once (well, it will handle the one after one internally) so that might be the better way to go. 
Unfortunatly I´m not too much into Web-Calls and APIs so I can´t create a pull but I can help you with testing later on if needed.

**Comment by LukeMarlin** [comment] 2019-08-19 14:21
Hi, sorry for the delay. I'll be taking care of that matter this week, next week in the worst case.

**Comment by LukeMarlin** [comment] 2019-09-04 09:47
@FabianZimbalev , PR was merged and version 3.3.0 should be available shortly on nuget.org.
Mind giving it a try?

**Comment by FabianZimbalev** [comment] 2019-09-04 10:10
Hi Luke,

as soon as NuGet tells me that there´s an update, I will.
Might take a few days though since I have other tasks but thank you for investigating, I´ll keep you updated.

Best regards,
Fabian

Von: Luke Marlin <notifications@github.com>
Gesendet: Mittwoch, 4. September 2019 11:48
An: ovh/csharp-ovh <csharp-ovh@noreply.github.com>
Cc: Fabian Zimbalev <Fabian.Zimbalev@crmaddon.com>; Mention <mention@noreply.github.com>
Betreff: Re: [ovh/csharp-ovh] WebClient not supporting concurrent I/O operations (#28)


@FabianZimbalev<https://github.com/FabianZimbalev> , PR was merged and version 3.3.0 should be available shortly on nuget.org.
Mind giving it a try?

**Comment by LukeMarlin** [comment] 2019-09-24 09:08
I'm closing the issue for now as this should be fixed by using `HttpClient`, feel free to reopen it if needed

**Closed as completed by LukeMarlin** 2019-09-24 09:08 UTC
Labels: bug
